### ISSUE TITLE
Could not find artifact io.prometheus.jmx:collector:jar:1.1.0 in central

### ISSUE THREAD

**Issue by brusdev** [prometheus/jmx_exporter#1086]
The artifact io.prometheus.jmx:collector:jar:1.1.0 is not in the Maven Central Repository, see https://repo1.maven.org/maven2/io/prometheus/jmx/collector/

**Comment by dhoard** [comment]
@brusdev historically (at least since version 0.4.0 / 2015... though probably earlier), the `collector` module jar has been published to Maven Central, but hasn't really been _supported_ as public project library.

It has Javadoc, but no API contract, documentation, etc. 

Changes to the public classes / class methods in `collector` have been kept minimal primarily to minimum risk.

I'm not opposed to publishing the `collector` module jar to Maven Central, but I feel that if we are going to support the `collector` as library then renaming, clean up, documentation, etc., needs to be done.

**Comment by ppatierno** [comment]
@dhoard first of all thanks for the explanation ... AFAICS the Strimzi project (withing the HTTP bridge) is not the only one using the collector that way. I can understand that it would mean more work, but at least continue to publish it would be a first step to take.
I would assume not all projects can run the java-agent or the exporter as standalone.

**Comment by dhoard** [comment]
@brusdev @ppatierno After discussing with the team...

- we will continue to publish the `collector` jar to Maven Central
- the `collector` 1.1.0 jar will be published to Maven Central
- it will be treated as an internal project library (no API documentation, API contract, etc.)
- classes, APIs, etc. are subject to change

I need to implement some Maven changes, but I hope to have the `collector` 1.1.0 jar in Maven Central within the next 7 days.

**Comment by ppatierno** [comment]
That's a great news @dhoard ! Thank very much to you and the team!

**Comment by dhoard** [comment]
@brusdev @ppatierno the `collector` 1.1.0 jar is now on Maven Central. Please test.

https://central.sonatype.com/namespace/io.prometheus.jmx

**Comment by ppatierno** [comment]
I tested it but also needed to bump the client to 1.3.4. It works fine, thanks for the effort!

**Comment by brusdev** [comment]
@dhoard thanks a lot!!!
