### ISSUE TITLE
Switch to plain http server

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/jmx_exporter#155]
Using jetty has caused a number of issues in this exporter. As JMX is more likely to be used with odd/old/unusual software, I think we should implement a httpserver exposition in client_java and then use that instead of jetty.

**Comment by leogomes** [comment]
Do you want any help with this?

Cheers,
Leo

**Comment by brian-brazil** [comment]
That'd be great, details are over in #156.

**Comment by brian-brazil** [comment]
Are you currently working on this @leogomes?

**Comment by leogomes** [comment]
@brian-brazil Haven't done much, but just tested using https://github.com/prometheus/client_java/pull/73 HTTPServer and it worked fine for my basic JMX settings. If I understood correctly you'd expect me to also clean-up that PR, so that it can be merged, right? Should we discuss there on what exactly needs to be done?

You can check how I used it here: https://github.com/leogomes/jmx_exporter/commit/16f3735714b1df19d6abc4d0f670eeaa1dcf4b7e

**Comment by brian-brazil** [comment]
I've just started working on cleaning up that PR. We won't get SO_REUSEADDR, but otherwise it seems workable.

**Comment by leogomes** [comment]
Other thing I noticed, comparing to the current implementation in JMX exporter, is that it doesn't allow you to specify the host only the port.

`mServer.bind(new java.net.InetSocketAddress(port), 3);`

It may be a problem for machines with multiple NICs.

**Comment by brian-brazil** [comment]
Both the agent and separate process currently support setting the host.

**Comment by leogomes** [comment]
Yes, they do, but not the HTTP server that is in the PR you're reviewing ;)

**Comment by brian-brazil** [comment]
https://github.com/prometheus/client_java/tree/httpserver is what I have so far

**Comment by leogomes** [comment]
OK, I can add the host thing once it's merged and modify my PR then. Let me know if you want me to do that.
