### ISSUE TITLE
Global label

### ISSUE THREAD

**Issue by moreiramarti** [prometheus/jmx_exporter#173]
Hi, 

Thanks for the exporter it is a great help for me.
Is it possible to add a global label for default jvm metrics (like instance or something) ?

I use the javaagent and I have multiple jvm to monitor.

Thanks,
Martinho

**Comment by brian-brazil** [comment]
This is considered an anti-pattern in Prometheus. You should do this with relabelling on the Prometheus end.

**Comment by jglapa** [comment]
I have the same problem. 
I have multiple jvms to monitor on the same server.
My plan was to start all the java processes with the agent and then run a cron job to save the metrics to disk.
From where I would read the files with `prometheus-node-exporter` text collector. 
The problem is that there is no way to differentiate the metrics from different jvms. I need this because prometheus cannot scrape every jvm individually. Policies don't allow to open so many ports and I want to avoid pushing the metrics over the gateway.
