### ISSUE TITLE
Cassandra job scrape example

### ISSUE THREAD

**Issue by VinceMD** [prometheus/jmx_exporter#182]
Using the jmx exporter and the example rules, I was able to get the metrics exposed on the endpoint.
Does someone have an example Prometheus scraping job I can use? I'm trying to come up with one but nothing is shown in Target.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

https://www.robustperception.io/monitoring-cassandra-with-prometheus/
