### ISSUE TITLE
Debug the HTTP server

### ISSUE THREAD

**Issue by mazzy89** [prometheus/jmx_exporter#191]
Any way to debug the HTTP server to print out in the console some meaningful message? I'm running into an issue. Kafka is running in a container and expose the port 5555. In another container I run the HTTP server in the port 5556 but when I try to curl `http://<container-name>:5556/metrics`  the request hang for few mins and then goes in time out. Any idea?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by mazzy89** [comment]
@brian-brazil gotcha. thank you for the quick reaction
