### ISSUE TITLE
Syntax for using jmx_prometheus_javaagent-0.10.jar ?

### ISSUE THREAD

**Issue by mikequentel** [prometheus/jmx_exporter#194]
I see the README says: `java -javaagent:./jmx_prometheus_javaagent-0.10.jar=1234:config.yaml -jar yourJar.jar` but sorry still not understanding how to use this.

Trying to scrape JMX metrics from an instance of Tomcat--I have confirmed that I can anonymously view the stats in JConsole with JMX port at `9999`. The `catalina.sh` includes:
```
CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=myserver.com -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=9999"
```

I was attempting to use syntax like this, though I do not know what `yourJar.jar` would be in this case:
`java -javaagent:./jmx_prometheus_javaagent-0.10.jar=8099:tomcat7.yml`

The `tomcat7.yml` looks like:
```
---
hostPort: localhost:9999
username:
password:

rules:
- pattern: ".*"
```

**Comment by mattrussi** [comment]
Hi @mikequentel, usually these questions are better suited for the [Prometheus-Users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

Regarding the syntax of the command to run, you can add the `-javaagent` parameter to your CATALINA_OPTS as simply as this: 

`CATALINA_OPTS="$CATALINA_OPTS -javaagent:./jmx_prometheus_javaagent-0.10.jar=8099:tomcat7.yml"`

The `yourJar.jar` is the JAR file of your application that you are executing. You don't necessarily have to include this `-jar` parameter depending on how you start your application. For Tomcat, just pass the `-javaagent` in your CATALINA_OPTS.

One thing to note about your `tomcat7.yml` config file, you don't need to include the `hostPort`, `username`, or `password` fields since you're running this as a `-javaagent`. Having just the following will be fine to start out with.

```
---
rules:
- pattern: ".*"
```

**Comment by mikequentel** [comment]
Thanks very much @mattrussi for clarifying the usage, as well as pointing out the mailing list. Can mark this closed.

**Comment by hr-ireh** [comment]
I tried to connect with the curl metric command but when I run a heavy load, they do not output.

Do you have an opinion?
