### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by szhilkin** [prometheus/jmx_exporter#207]
Hi ! 
I have several nodes with jmx_exporter running as java agent with tomcat. Due to security restrictions, I use nginx tp proxy metrics outside. 

With version 0.10 all works fine, but with 0.1.0 Prometheus scrape gives "unexpected EOF" 

When I use curl to test metrics, all works fine too.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by np5** [comment]
You should use the correct `Accept` and `Accept-Encoding` headers if you are debugging with curl.

It seems there is an issue with the gzip encoding and HTTP 1.0. Nginx thinks that the backend closes the connection too early, because it doesn't receive all the expected content.

Workaround: use `proxy_http_version 1.1;`
