### ISSUE TITLE
kafka jmx_exporter hang infinitum on polling

### ISSUE THREAD

**Issue by uriklagnes** [prometheus/jmx_exporter#225]
I have jmx_exporter for kafka (using sample config) running fin on port 7070, but it never returns to /metrics request:

```
urik@kafka-1:~$ curl http://localhost:7070/metrics
urik@kafka-1:~$ ... waiting forever

```

This is the most recent jmx_exporter, downloaded today.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
