### ISSUE TITLE
Using exporter with CompositeData[] objects?

### ISSUE THREAD

**Issue by AravindaM** [prometheus/jmx_exporter#232]
Hi, Is this supported. If yes how to configure it. Doesn't seems to be working with default pattern,

`pattern: ".*"`

**Comment by brian-brazil** [comment]
Yes.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by AravindaM** [comment]
@brian-brazil Sure will do. Thanks
