### ISSUE TITLE
High CPU spikes

### ISSUE THREAD

**Issue by sidSingla** [prometheus/jmx_exporter#241]
I setup JMX metrics and I am seeing sudden CPU spike at my Kafka boxes from 20% to 95%. Kafka cluster has 7 nodes and each node has 4 cores. 
Is this a known issue and what is the reason for the hike?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by garmes-gdev** [comment]
@sidSingla find you a solution ?? I am interesting, I am facing the same issue

**Comment by stephankoelle** [comment]
I thinks those spikes a wrong monitoring from the JMX agent, the node agent does not show them.
