### ISSUE TITLE
Problem collecting metrics from Kafka Connect

### ISSUE THREAD

**Issue by rguderlei** [prometheus/jmx_exporter#255]
With v 1.0.0, Kafka Connect has dramatically improved its monitoring capabilities. We are currently trying to get the Kafka Connect metrics into Prometheus via the JMX exporter. Most of it is working fine but the status metric is failing:

`Mar 12, 2018 4:14:12 PM io.prometheus.jmx.JmxCollector$Receiver recordBean
FINE: Ignoring unsupported bean: kafka.connect<type=connector-task-metrics, connector=foo, task=0><>status: running`

It seems that the JMX exporter does not support Strings (JmxCollector.java line 375ff). I'm not too familiar with Prometheus, therefore I'm not sure whether that is by design or not. The status of a Connect Task is quite interesting so we are investigating solutions on either the Prometheus or the Kafka side of things.

Is failing on String valued metrics intended behaviour or not?
Thanks a lot in advance!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by tooptoop4** [comment]
@rguderlei did u solve getting string metrics?
