### ISSUE TITLE
Export of java.lang.String Values not possible

### ISSUE THREAD

**Issue by svenbs** [prometheus/jmx_exporter#266]
Hi,

I want to export JMX-Metrics from a solr-instance but it seems like java.lang.String types will not be exported by the jmx-exporter.

This is my pattern:
```
- pattern: '(solr.*)<type=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]).*><>(replicationFailedAt|indexReplicatedAt):'
  name: $1_$2_$3
```

And this is the Attribute I want to export:
```
ObjectName: solr/live:type=/replication,id=org.apache.solr.handler.ReplicationHandler
```

Regards,
Sven

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by svenbs** [comment]
Hi @brian-brazil,

thanks for your response.

I don't know if you got my issue right. The problem is, that the jmx-exporter won't export values which are typed as a string in jmx. Even if the string contains a number it is not exported. So I cannot use the metric to monitor my system.

Types like java.lang.Double, java.lang.Long are exported fine.

Regards,
Sven
