### ISSUE TITLE
Get wrong value of "kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent" when using jmx_exporter with kafka-0-8-2.yml

### ISSUE THREAD

**Issue by billyhu** [prometheus/jmx_exporter#268]
I am using the exporter with kafka-0-8-2.yml to collect metrics from confluentinc/cp-kafka:3.2.0, and I get the value of this metric
"kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent" which is a very large integer number not a float number between 0 and 1. And I don't know what the value means.
Could I use other metrics to calculate the value of this metric?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
