### ISSUE TITLE
Authentification Failed with the run_sample_httpserver

### ISSUE THREAD

**Issue by Ozymandiiaz** [prometheus/jmx_exporter#270]
I am getting 
May 09, 2018 11:31:44 AM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.lang.SecurityException: Authentication failed! Credentials required

even if i define the user and password in the config.

#!/usr/bin/env bash
# Script to run a java application for testing jmx4prometheus.

version=$(sed -n -e 's#.*<version>\(.*-SNAPSHOT\)</version>#\1#p' pom.xml)

# Note: You can use localhost:5556 instead of 5556 for configuring socket hostname.
java -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.port=5555 -jar jmx_prometheus_httpserver/target/jmx_prometheus_httpserver-${version}-jar-with-dependencies.jar 5556 example_configs/httpserver_sample_config.yml

startDelaySeconds: 0
hostPort: cass.test:7199
ssl: False
user: "test"
password: "test"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
