### ISSUE TITLE
Running with an OSGi container

### ISSUE THREAD

**Issue by anandsourabh** [prometheus/jmx_exporter#271]
Hello,

Does anyone have experience with jmx exporter within an OSGI container? I am looking at integrating with Adobe Experience Manager.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
