### ISSUE TITLE
run javaagent error

### ISSUE THREAD

**Issue by haozi4263** [prometheus/jmx_exporter#276]
java -javaagent:jmx_prometheus_javaagent-0.3.1.jar=8080:jvm.yaml -jar jmx_prometheus_javaagent-0.3.1.jar

no main manifest attribute, in jmx_prometheus_javaagent-0.3.1.jar

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by morganwalker** [comment]
@haozi4263 I have the same issue and didn't see any related posts on the mailing list. Were you able to resolve this?

**Comment by mootezbessifi** [comment]
any fix for this ?
