### ISSUE TITLE
Notice config file changes

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/jmx_exporter#29]
If the config file changes, we should reload it rather than having to restart the process

**Comment by andersschuller** [comment]
Did you already have some thoughts about how you would implement this? From some quick research, it seems like the best option is to use the [`WatchService`](http://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchService.html), but this is only available from Java 7. If you want to maintain compatibility with Java 6, it looks like one of the options is to use this [`FileMonitor`](http://commons.apache.org/proper/commons-vfs/apidocs/org/apache/commons/vfs2/impl/DefaultFileMonitor.html) instead, but that involves polling the file system instead of receiving events.

**Comment by brian-brazil** [comment]
About half of our users are still using Java 6, so we need to maintained compatibility there. SOmething as simple as checking the mtime on every scrape would be fine.

**Comment by brian-brazil** [comment]
This was done.
