### ISSUE TITLE
[Question] Could jmx_exporter get metrics from 2 cassandra instances on 1 host?

### ISSUE THREAD

**Issue by vitalygusev** [prometheus/jmx_exporter#298]
If there are 2 cassandra instances on 1 host with 2 different jmx ports (7198 and 7199), could jmx_exporter monitor both of them?

**Comment by brian-brazil** [comment]
No, you need to have one java agent each.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
