### ISSUE TITLE
jmx_exporter as a thread

### ISSUE THREAD

**Issue by muthuveerappan** [prometheus/jmx_exporter#308]
Hi Team , 

Can we start the jmx exporter as a thread in my application. 

If possible, could you provide as a java code snippet. 

Thanks and Regards.,
Muthuveerappan

**Comment by blublinsky** [comment]
Or can we make sure that it runs as a daemon thread, so that it terminates when the main app (Spark) exits

**Comment by muthuveerappan** [comment]
ya, that will work, how do we achieve that.  Can you share a java snippet. I am yet to look at the jmx_exporter source. 

fyi - we have a micro service application.  A container (docker image) will only have a single process (java) . Currently this process is mult-threaded. We plan to start promethes client/exporter as thread.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
