### ISSUE TITLE
JMX Timer type support

### ISSUE THREAD

**Issue by skonto** [prometheus/jmx_exporter#309]
Is JMX timer supported? Spark exposes several metrics of this type.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
