### ISSUE TITLE
Activemq  monitor jmx_exporter

### ISSUE THREAD

**Issue by muzili1** [prometheus/jmx_exporter#310]
I want to know if there is monitoring of Activemq.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
