### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by YoannDBA** [prometheus/jmx_exporter#323]
Hello, i just start with Grafana/Prometheus/JMX-Exporter.
So i install Grafana, Prometheus, i plug prometheus on grafana with sucess.
So i want to install the jmx_exporter on my cassandra node...
But i really don't understand how can i do, can you help me or give me a link who give the procedure please?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by YoannDBA** [comment]
I understand your opignon, but it's a JMX-Exporter problem not with Prometheus.
Can you explain/give me the procedure please?
