### ISSUE TITLE
how get jvm_cpu status information?

### ISSUE THREAD

**Issue by orclcast** [prometheus/jmx_exporter#336]
hi:
    How to get the cv running status information of jvm?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by perlun** [comment]
For reference, this thread has some information about this: https://groups.google.com/forum/#!searchin/prometheus-users/cpu$20java%7Csort:date/prometheus-users/MuVf-vK4T-I/CvajoSf1BQAJ
