### ISSUE TITLE
Don't know how to get kafka lag & message data.

### ISSUE THREAD

**Issue by xzg121** [prometheus/jmx_exporter#341]
Environment:
CentOS 7.4
jmx_exporter 0.6
kafka 2.11

Problem:
I'm using jmx_exporter and prometheus to monitor kafka and hoping to get kafka_lag and message data, how should I config?

For example:
KAFKA_LAG   the lag kafka holds
KAFKA_CURRENT_OFFSET  the message kafka has total consumed
KAFKA_LOG_END_OFFSET  the total  kafka message

Let me konw if any further information is needed.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
