### ISSUE TITLE
Blacklist mbeans which have 'applies-to'  string part of name

### ISSUE THREAD

**Issue by Vatsaldhar26** [prometheus/jmx_exporter#342]
How to ignore the mbeans which have 'applies-to' in their name, e.g. 

"jboss.as:core-service=management,access=authorization,constraint=sensitivity-classification,type=core,classification=security-realm-ref,applies-to="/core-service=management/management-interface=http-interface""

blacklist mbean names like these, which have applies-to

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
