### ISSUE TITLE
kafka kafka_network_requestmetrics_* look wrong

### ISSUE THREAD

**Issue by enyamada** [prometheus/jmx_exporter#349]
In order to collect Kafka metrics I'm using jmx_prometheus_javaagent-0.6.jar with https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/kafka-0-8-2.yml and Kafka 0.10.2.1.

Seems like kafka kafka_network_requestmetrics_* look wrong -- they all have the same value for me. For example:

kafka_network_requestmetrics_totaltimems{request="ApiVersions",} 156.0
kafka_network_requestmetrics_localtimems{request="ApiVersions",} 156.0
kafka_network_requestmetrics_responsequeuetimems{request="ApiVersions",} 156.0
kafka_network_requestmetrics_throttletimems{request="ApiVersions",} 156.0
kafka_network_requestmetrics_requests_total{request="ApiVersions",} 156.0
kafka_network_requestmetrics_remotetimems{request="ApiVersions",} 156.0
kafka_network_requestmetrics_responsesendtimems{request="ApiVersions",} 156.0
kafka_network_requestmetrics_requestqueuetimems{request="ApiVersions",} 156.0

Is there possibly some issue with the config file? (https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/kafka-0-8-2.yml )

thanks.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
