### ISSUE TITLE
jmx_exporter as an agent on windows server problem

### ISSUE THREAD

**Issue by captaingoodguy** [prometheus/jmx_exporter#356]
I've already exposed JMX within Java on port 8999,
![8999](https://user-images.githubusercontent.com/34262723/53469657-c883d100-3a99-11e9-888f-8583b648458b.jpg)

and this is my prometheus-jmx.yml
![yml](https://user-images.githubusercontent.com/34262723/53469798-5495f880-3a9a-11e9-83b2-7c176100fb9b.jpg)

then i run jmx_prometheus_javaagent-0.11.0.jar in powershell ,got this  issue
can not load .sun.management.jmxremote
![1551248400 1](https://user-images.githubusercontent.com/34262723/53469925-c9693280-3a9a-11e9-9067-805bb6a0c718.jpg)

and my catalina.bat's setting 
![1551248489 1](https://user-images.githubusercontent.com/34262723/53470001-16e59f80-3a9b-11e9-80de-5e61f4a27bf9.jpg)

how could i do now? pls help.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
