### ISSUE TITLE
java agent cause kafka cpu use high

### ISSUE THREAD

**Issue by xingmin860818** [prometheus/jmx_exporter#365]
java agent version: jmx_prometheus_javaagent-0.3.0.jar
kafka config : kafka-2_0_0.yml
kafka : export KAFKA_OPTS="-javaagent:/data/tools/jmx_prometheus_javaagent-0.3.0.jar=7071:/data/tools/kafka-2_0_0.yml"

I use this configurations , It usually cause the kafka node cpu usage and load high. Then I use htop to find the highest thread ,and use strace -p ppid to  track the threads ,I found it invoke the getrusage() method so quickly , and cause the kafka node cpu usage very high . By the way , the kafka instance jvm usage is common.  

What cause this problem and how can I avoid it ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by superfenv** [comment]
> java agent version: jmx_prometheus_javaagent-0.3.0.jar
> kafka config : kafka-2_0_0.yml
> kafka : export KAFKA_OPTS="-javaagent:/data/tools/jmx_prometheus_javaagent-0.3.0.jar=7071:/data/tools/kafka-2_0_0.yml"
> 
> I use this configurations , It usually cause the kafka node cpu usage and load high. Then I use htop to find the highest thread ,and use strace -p ppid to track the threads ,I found it invoke the getrusage() method so quickly , and cause the kafka node cpu usage very high . By the way , the kafka instance jvm usage is common.
> 
> What cause this problem and how can I avoid it ?

hello,xingmin860818 
   i have the same problem,did you ask you to solve it?

**Comment by wl4g** [comment]
Did you solve it? I also encountered the same problem

**Comment by wl4g** [comment]
![image](https://user-images.githubusercontent.com/29530154/145160290-881a2f1b-20bf-4884-837b-93ac7e74acb5.png)

**Comment by fstab** [comment]
`jmx_exporter` is just sitting there doing nothing until the Prometheus server scrapes metrics. When the Prometheus server scrapes, the `jmx_exporter` loads the JMX beans, applies the rules from the config, and provides the resulting metrics in the response to the HTTP request. After the request is done, `jmx_exporter` is idle again.

If this is actually caused by Prometheus scrapes, reduce the scrape interval. If you see load after the Promtheus scrape is done, then this might be caused by something else not related to `jmx_exporter`.
