### ISSUE TITLE
JMX Agent key is case sensitive？？？

### ISSUE THREAD

**Issue by adminops** [prometheus/jmx_exporter#367]
JMX Agent key is case sensitive？？？

kafka:
java_lang_operatingsystem_freephysicalmemorysize   

zookeeper
java_lang_OperatingSystem_FreePhysicalMemorySize

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
