### ISSUE TITLE
Which file is used for spring mybatis project?

### ISSUE THREAD

**Issue by xiaoyaolaotou** [prometheus/jmx_exporter#375]
Which yml file is used by the micro my service in the spring mybatis project? Is it tomcat.yml?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
