### ISSUE TITLE
Metrics per broker

### ISSUE THREAD

**Issue by simPod** [prometheus/jmx_exporter#376]
Is it possible to add broker label to metrics and if so, how? I'd like to eg. graph underreplicated partitions or leader counts per broker. Thanks!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
