### ISSUE TITLE
How to write patten for HDFS Namenode TopUserOpCounts jmx metrics?

### ISSUE THREAD

**Issue by liufang94** [prometheus/jmx_exporter#385]
Data example:
{
"name": "Hadoop:service=NameNode,name=FSNamesystemState",
"TopUserOpCounts": "{
  "timestamp": "2019-05-10T20:43:02+0000",
  "windows": [
    {
      "ops": [
        {
          "opType": "rename",
          "topUsers": [
            {
              "user": "franklee",
              "count": 16
            }
          ],
          "totalCount": 16
        },
        ...
      ]
      "windowLenMs": 1500000
    }
  ]
}

We want to emit metrics like following:
name: namenode_fsnamesystemstate_topuseropcounts_totalcount   // value is 16
labels:
  optype: "rename"
  windowLenMs: 1500000

name: namenode_fsnamesystemstate_topuseropcounts_count   // franklee
labels:
  optype: "rename"
  windowLenMs: 1500000
  user: "franklee"

I am not able to find such examples. Is this supported?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
