### ISSUE TITLE
Java agent not running

### ISSUE THREAD

**Issue by chithanh89** [prometheus/jmx_exporter#386]
Hi guys,

I have a helloworld.jar and follow the instruction of github, when i run it's only print "helloworld" to screen but not have a metrics link. I check on machine, port of agent also not running.
Can someone tell me what i did wrong?
Tks so much.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
