### ISSUE TITLE
Error opening zip file or JAR manifest missing : ./jmx_prometheus_javaagent-0.12.0.jar

### ISSUE THREAD

**Issue by itantiger** [prometheus/jmx_exporter#402]
i had successfully used jmx_prometheus_javaagent-0.12.0.jar  in kafka ,but i used it in hiveserver this problem has arisen.more error info is:Error occurred during initialization of VM agent library failed to init: instrument. 
my java version is 1.8.0_181

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
