### ISSUE TITLE
 deploy a jmx_exporter on one machine and then collect the JVM on multiple machines

### ISSUE THREAD

**Issue by gentlezuo** [prometheus/jmx_exporter#403]
I want to deploy a jmx_exporter on one machine and then collect the JVM on multiple machines.

Can I achieve it ?
The config.yaml  is as follows:
```
jmxUrl:
-  service:jmx:rmi:///jndi/rmi://10.29.xx.20:1234/jmxrmi
-  service:jmx:rmi:///jndi/rmi://10.29.xx.21:4321/jmxrmi
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
