### ISSUE TITLE
Cannot start JMX on Centos7

### ISSUE THREAD

**Issue by yasirk** [prometheus/jmx_exporter#408]
been trying to get JMX to start but it simply wont go past the following, what am i missing?

sudo /usr/jdk64/jdk1.8.0_112/bin/java  -javaagent:/home/hdfuser/jmx_prometheus_javaagent-0.12.0.jar=8080:/home/hdfuser/config.yaml

Usage: -javaagent:/path/to/JavaAgent.jar=[host:]<port>:<yaml configuration file>

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
