### ISSUE TITLE
export jmx data to remote URL

### ISSUE THREAD

**Issue by kyaparla** [prometheus/jmx_exporter#411]
Running as a java agent, cant it send data on a schedule to remote address? like prometheus server?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
