### ISSUE TITLE
JMX Exporter to Prometheus for Kotlin

### ISSUE THREAD

**Issue by ruchirnaphade** [prometheus/jmx_exporter#412]
I am trying to use JMX Exporter for my kotlin application (with Maven). I have gone through https://github.com/prometheus/jmx_exporter, https://www.openlogic.com/blog/monitoring-java-applications-prometheus-and-grafana-part-1 these articles and trying to do the same way. My problem is, I don't understand how and where to add JVM parameters in my application (Java agent).

I have downloaded .jar file and added it to root/prometheus folder. Moreover, I have created config.yml file according to these articles and also put it in same folder.

I just want to know where should configure below:

`-javaagent:/path/to/jmx_exporter_jar/jmx_prometheus_javaagent-0.3.1.jar=[HTTP PORT]:/path/to/jmx_exporter_config/config.yml`

Could anyone please assist me with this?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
