### ISSUE TITLE
Help with Tomcat Active Sessions metrics

### ISSUE THREAD

**Issue by svetoslavsimeonov1987** [prometheus/jmx_exporter#418]
Hello guys, can someone help me with exporting tomcat metrics to prometheus?
What I did so far:
1. Added jmxremote, jmxremote.port=2500, jmxremote.ssl=false and authentication=false to Apache tomcat service.
2. Started a java process on that port that fetches the metrics:
java -jar jmx_prometheus_httpserver-0.12.0-jar-with-dependencies.jar 2505 config.yaml
3. Config yaml includes:
---
startDelaySeconds:0
jmxUrl:service:jmx:rmi:///jndi/rmi://127.0.0.1:2500/rmxrmi
ssl:false
lowercaseOutputLabelNames:true
lowercaseOutputName:true:
rules:
-pattern:'.*'

I get some metrics but on tomcat_activesessions metric I get always 0.
![image](https://user-images.githubusercontent.com/32739597/63592754-0f6f0100-c5bb-11e9-93a6-6f9dfe31287f.png)
![image](https://user-images.githubusercontent.com/32739597/63592776-1eee4a00-c5bb-11e9-84df-80664bcbd6ef.png)

Can you please advise?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
