### ISSUE TITLE
How can I get metrics of jmx functions using jmx_exporter

### ISSUE THREAD

**Issue by rashmipatnaik** [prometheus/jmx_exporter#422]
Hi, I have some jmx function with no input parameter, how can I get metrics of output of those functions?

I tried the the following pattern but no luck
domain<beanpropertyName1=beanPropertyValue1, beanpropertyName2=beanPropertyValue2, ...><>functionName()

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
