### ISSUE TITLE
Metrics available via JMX but not exported by the Prometheus agent

### ISSUE THREAD

**Issue by bratmito** [prometheus/jmx_exporter#423]
Hi,

I am using the jmx exporter for prometheus with Kafka (version 2.1.1) with the sample configuration file (kafka-2_0_0.yml).
When I connect with jconsole to the JMX port I see metrics which are not available in the exported data by the jmx_exporter.
For example the object 
![image](https://user-images.githubusercontent.com/6877954/63862029-9e618c00-c9b4-11e9-9869-f38b74add61f.png)

Should match the expression: 
> - pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
  name: kafka_server_$1_$2
  type: GAUGE

but still, i don't see any ConsumerLag metrics in the exported data by the jmx_exporter.
Is this a bug or I am missing something?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
