### ISSUE TITLE
How to run the prometheus jmx-exporter stand alone?

### ISSUE THREAD

**Issue by hramadur** [prometheus/jmx_exporter#426]
Anyone has instructions on how to run this prometheus jmx-exporter  stand alone ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by akamensky** [comment]
Given that this is a top link in Google search for "how to run jxm-exporter standalone" I don't think simple "go look elsewhere" style answers are good. At least put it in the docs.
