### ISSUE TITLE
Expose metrics on https endpoint

### ISSUE THREAD

**Issue by jaibheem** [prometheus/jmx_exporter#428]
Can we have jmx_exporter expose the collected metrics on a https end point instead of http?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
