### ISSUE TITLE
metric for CPU utilization by java process

### ISSUE THREAD

**Issue by anishshaw** [prometheus/jmx_exporter#432]
Hello,

Is it possible for get the CPU utilization by a java process ? if yes then please help me with the name of metric for it.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by perlun** [comment]
For reference, this thread has some information about this: https://groups.google.com/forum/#!searchin/prometheus-users/cpu$20java%7Csort:date/prometheus-users/MuVf-vK4T-I/CvajoSf1BQAJ
