### ISSUE TITLE
Host as Tag for each metric

### ISSUE THREAD

**Issue by juliofalbo** [prometheus/jmx_exporter#439]
Hi.

I would like to know if it is possible to add a tag with the host in each metric that will be exported via JMX Exporter.

If it is not, could be a great idea add this option!

My scenario:

I have 3 JVM that I want to monitor, but they are in different spot instances, so, the hosts are dynamic, and the Prometheus only accept a fixed host in the `prometheus.yaml`. 
My idea is creating a middleware to merged my 3 metrics into one using a target like `instance` or `host` to show in the Grafana via Prometheus

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
