### ISSUE TITLE
Is it safe to grab metrics via JMX in production?

### ISSUE THREAD

**Issue by nartamonov** [prometheus/jmx_exporter#441]
Hi!

Documentation for Dropwizard metrics contains [interesting warning](https://metrics.dropwizard.io/4.1.0/manual/core.html#jmx) about using JMX: "We don’t recommend that you try to gather metrics from your production environment. *JMX’s RPC API is fragile and bonkers*. For development purposes and browsing, though, it can be very useful."

I wonder is it applicable to jmx_exporter?

Thanks!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by thiloplanz** [comment]
Did that discussion on the mailing list lead to a conclusion?
Here is the thread: https://groups.google.com/d/topic/prometheus-users/-PMNSH7nNSQ/discussion

When run as the Java agent, that "fragile and bonkers" JMX RPC API is not being used, right? The agent queries JMX in-process and exposes the results via HTTP?
