### ISSUE TITLE
Embedded agent stops responding after some time

### ISSUE THREAD

**Issue by wundrian** [prometheus/jmx_exporter#446]
I've deployed the exporter (version 0.12.0) as a java agent on my dockerized JVM. On startup, I exec into the container and use `curl` to request metrics from `127.0.0.1:8080/metrics`. This succeeds just fine for about 3 to 4 attempts.

Regardless of the number of queries, after about 2 minutes the endpoint returns an empty page.

I've gotten a thread dump, showing two jmxtrans threads idle. Is there anything I could do help debug this?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by wundrian** [comment]
For the benefit of somebody finding this, for me it was my JVM's SecurityManager I've setup to be very restrictive. The javaagent sets up a watch for the config file. If that read doesn't succeed apparently things go sideways. Moving the config file into a directory SecurityManager would allow reading from fixed this.
