### ISSUE TITLE
no main manifest attribute, in ./jmx_prometheus_javaagent-0.12.0.jar when running the javaagent jar

### ISSUE THREAD

**Issue by mootezbessifi** [prometheus/jmx_exporter#448]
Hi All,

I downloaded the jar file mentioned in read me and run the following cmd like mentioned in the instructions:

`java -jar ./jmx_prometheus_javaagent-0.12.0.jar -javaagent:./jmx_prometheus_javaagent-0.12.0.jar=8080:./config.yaml`

but i got the below error:

`no main manifest attribute, in ./jmx_prometheus_javaagent-0.12.0.jar`

i downloaded the java src in the project and find out that really the agent project does not contain `main` class !

I have big doubts how this is working ?
please tell me about the correct way to run it.
thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by mootezbessifi** [comment]
Sorry but this looks like a bug in the java code. Otherwise what is the purpose of opening issues here. !!!
