### ISSUE TITLE
Is it possible to add example config for standard JVM beans?

### ISSUE THREAD

**Issue by debedb** [prometheus/jmx_exporter#452]
This is more like a request for help, but unsure where to direct it. I am having trouble with standard JVM beans, for example, given these rules:

`
rules:
  - pattern: 'java.lang:type=OperatingSystem,OpenFileDescriptorCount'
  - pattern: 'java.lang:type=OperatingSystem,SystemLoadAverage'
  - pattern: 'java.lang:type=OperatingSystem,SystemCPULoad'
  - pattern: 'java.lang:type=OperatingSystem,ProcessCPULoad'
`
I do get the FD count but not the rest. For memory usage, these work as I wanted:

`
  - pattern: 'java.lang:type=Memory,HeapMemoryUsage<used=(\w)>'
    value: $1
  - pattern: 'java.lang:type=Memory,NonHeapMemoryUsage<used=(\w)>'
    value: $1
`

But I cannot figure out how to get garbage collection metrics (in particular, say, I wanted java_lang_GarbageCollector_LastGcInfo_duration{name="ParNew",} and java_lang_GarbageCollector_CollectionTime ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
