### ISSUE TITLE
Ability of adding label globally

### ISSUE THREAD

**Issue by dashcheulov** [prometheus/jmx_exporter#454]
Hello!
I have pressing need to distinguish instances of exporters by comprehensible name. I cannot achieve this from side of prometheus-operator. A solution is to populate label to config of jmx_exporter and add it to metrics.

Is there an ability to add labels to all exported metrics gracefully? Probably I can write default rule for jvm metrics and put section 'labels' in it? Please, suggest one.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
