### ISSUE TITLE
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'

### ISSUE THREAD

**Issue by ChethanUK** [prometheus/jmx_exporter#462]
I am getting following error:

```bash
k log -n kafka kafka-schema-registry-7bd979fddb-7m7vr -c prometheus-jmx-exporter -f
+ kubectl log -n kafka kafka-schema-registry-7bd979fddb-7m7vr -c prometheus-jmx-exporter -f
log is DEPRECATED and will be removed in a future version. Use logs instead.
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
