### ISSUE TITLE
Question - Is it possible to get jvm.gc.alloc

### ISSUE THREAD

**Issue by skumarm8** [prometheus/jmx_exporter#468]
Hi,

Is it possible to get jvm.gc.alloc - An approximation of the total amount of memory, in bytes, allocated in heap memory.

I couldn't see the field related to getting jvm.gc.alloc in jvm metrics. Is there a way to get these field ?

Thanks,
Sathish M

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by skumarm8** [comment]
Thanks for the quick response. Will post over there.

Thanks,
Sathish M
