### ISSUE TITLE
Export tags from mbeans

### ISSUE THREAD

**Issue by bobrik** [prometheus/jmx_exporter#47]
HBase exports tags for some mbeans:

``` json
{
    "name" : "Hadoop:service=HBase,name=JvmMetrics",
    "modelerType" : "JvmMetrics",
    "tag.Context" : "jvm",
    "tag.ProcessName" : "RegionServer",
    "tag.SessionId" : "",
    "tag.Hostname" : "pewpew",
    "MemNonHeapUsedM" : 93.03323,
    "MemNonHeapCommittedM" : 94.578125,
    "MemNonHeapMaxM" : -9.536743E-7,
    "MemHeapUsedM" : 3626.3154,
    "MemHeapCommittedM" : 5279.8945,
    "MemHeapMaxM" : 8000.6875,
    "MemMaxM" : 8000.6875,
    "GcCountParNew" : 6348,
    "GcTimeMillisParNew" : 177628,
    "GcCountConcurrentMarkSweep" : 13,
    "GcTimeMillisConcurrentMarkSweep" : 698,
    "GcCount" : 6361,
    "GcTimeMillis" : 178326,
    "ThreadsNew" : 0,
    "ThreadsRunnable" : 20,
    "ThreadsBlocked" : 0,
    "ThreadsWaiting" : 69,
    "ThreadsTimedWaiting" : 26,
    "ThreadsTerminated" : 0,
    "LogFatal" : 0,
    "LogError" : 0,
    "LogWarn" : 0,
    "LogInfo" : 0
  }
```

Here I'm interested in `tag.ProcessName` being `RegionServer`. For master server I care about `tag.isActiveMaster` being `true` or `false`.

I'd like to have an ability to export these into labels somehow.

**Comment by brian-brazil** [comment]
For ProcessName, I suspect you should be doing that as a target label from your service discovery rather than from the target itself.

For the others, what I was thinking is that you could define the value of a metric to also come from the regex. This would let you put a 1 in for it, and also pull a label out.

**Comment by bobrik** [comment]
> For ProcessName, I suspect you should be doing that as a target label from your service discovery rather than from the target itself.

I don't understand what you mean by that. Can you explain in a bit more detail?

Did you mean that I should make metric `hadoop.hbase.jvm.regionserver` instead of `hadoop.hbase.jvm{process="regionserver"}`?

> For the others, what I was thinking is that you could define the value of a metric to also come from the regex. This would let you put a 1 in for it, and also pull a label out.

```json
{
    "name" : "Hadoop:service=HBase,name=Master,sub=Server",
    "tag.isActiveMaster" : "false",
    "numRegionServers" : 0,
    "numDeadRegionServers" : 0,
    "clusterRequests" : 0
  }
```

I have `Hadoop<service=HBase, name=Master, sub=Server><>numRegionServers` to apply regex on. I don't see how to extract `tag.isActiveMaster` from that.

**Comment by brian-brazil** [comment]
> I don't understand what you mean by that. Can you explain in a bit more detail?

You shouldn't be pulling this from the jvm itself, rather your monitoring should already know that this is a regionServer.

> I don't see how to extract tag.isActiveMaster from that.

The value comes after that, so you can limit a rule to only match certain values of that attribute. What's missing at the moment is a way to put in a value in that case.

**Comment by bobrik** [comment]
> You shouldn't be pulling this from the jvm itself, rather your monitoring should already know that this is a regionServer.

Okay, it is doable, although I'd prefer simpler approach of adding an extra label from bean.

> The value comes after that, so you can limit a rule to only match certain values of that attribute. What's missing at the moment is a way to put in a value in that case.

Okay, `Hadoop<service=HBase, name=Master, sub=Server><>numRegionServers 0.0`.

How do I infer from that info if it's a current master or a standby?

**Comment by brian-brazil** [comment]
You'd be looking at `Hadoop<service=HBase, name=Master, sub=Server><>tag.isActiveMaster: false`

**Comment by bobrik** [comment]
It doesn't work for me. I changed code in JMXCollector:

```
          String matchName = beanName + (rule.attrNameSnakeCase ? attrNameSnakeCase : attrName);
          System.out.println("!!!!! " + matchName + ": " + value);
```

Output I get (I assume that these are strings that are matched):

```
!!!!! Hadoop<service=HBase, name=Master, sub=Server><>masterActiveTime: 0
!!!!! Hadoop<service=HBase, name=Master, sub=Server><>masterStartTime: 1450355109902
!!!!! Hadoop<service=HBase, name=Master, sub=Server><>averageLoad: 0.0
!!!!! Hadoop<service=HBase, name=Master, sub=Server><>numRegionServers: 0
!!!!! Hadoop<service=HBase, name=Master, sub=Server><>numDeadRegionServers: 0
!!!!! Hadoop<service=HBase, name=Master, sub=Server><>clusterRequests: 0
```

I don't see tags here to match. What did I miss?

**Comment by brian-brazil** [comment]
This is how I propose to handle this, it isn't implemented yet.

**Comment by bobrik** [comment]
Ah, sorry, I misunderstood you. Looking forward to seeing this implemented!

**Comment by icetrain** [comment]
I have started working on this features (overriding bean value with either static value or regexp capture group) as I found a need for it myself. If time permits I should be able to produce a PR in a few days.

I was thinking of just adding a new optional config option under rules called "value: " with the same replace behavior as labels. If this option is omitted then everything works as it does today.

I haven't done any testing yet but there may be a global performance impact as a result of this since for it to work the rules must now process string values as well in addition to the current types.

Any thoughts on how to implement this best?

**Comment by brian-brazil** [comment]
The actual JMX bits are slowest, so I wouldn't worry too much about performance. Throw it at a Cassandra to see if there's any real effect, it's one of the slowest.

One other thing I've always wanted to do with values is to be able to multiply/divide them, so that milliseconds can be converted to second etc.

**Comment by icetrain** [comment]
Maybe run the config options value through something like http://www.objecthunter.net/exp4j? That would give all kinds of options for value transformation.

**Comment by brian-brazil** [comment]
That's probably going too far, just being able to apply a factor would be enough. Any real heavy lifting is best done in Prometheus.
