### ISSUE TITLE
Enable jmx_exporter for Gerrit

### ISSUE THREAD

**Issue by kirhie** [prometheus/jmx_exporter#471]
Can we please enable jmx_exporter for Gerrit like it works for Jenkins?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
