### ISSUE TITLE
FATAL ERROR in native method: processing of -javaagent failed

### ISSUE THREAD

**Issue by zenglingmin168** [prometheus/jmx_exporter#479]
FATAL ERROR in native method: processing of -javaagent failed

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
