### ISSUE TITLE
how to convert attributes into labels?

### ISSUE THREAD

**Issue by rahulbats** [prometheus/jmx_exporter#480]
i have a metric with a lot of attributes.
I want to export that into prometheus with labels 
For instance i have a object with objectname containing type=status, connector=something,task=something
but it has attributes WorkerId, Trace and State

if i use a rule like this, it does not work.
 - pattern: "com.connect.task<type=status, connector=([^:]+), task=([^:]+,WorkerId: ([^:]+),Trace: ([^:]+))><>State: ([^:]+)"
      name: "com_connect_connector_task_status"
      value: 1
      labels:
        connector: $1
        task: $2
        status: $3
        worker_id: $4
        trace: $5

How are users supposed to get attributes into labels

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
