### ISSUE TITLE
Extract WebSphere ND MBean metrics

### ISSUE THREAD

**Issue by williamzhao1979** [prometheus/jmx_exporter#486]
We need example config for WebSphere ND 9.
I can only get generic JVM metrics. How can I get all WebSphere metrics too.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
