### ISSUE TITLE
can not add javaagent to elastic search

### ISSUE THREAD

**Issue by gjie1991** [prometheus/jmx_exporter#487]
add -javaagent:./jmx_prometheus_javaagent-0.12.0.jar=8080:config.yaml to jvm.options

request localhost:8080 not work

ERR_CONNECTION_RESET

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
