### ISSUE TITLE
./run_sample_httpserver.sh doesn't listen on port 8080

### ISSUE THREAD

**Issue by ferenc0521** [prometheus/jmx_exporter#493]
mvn test running successfully, ./run_sample_httpserver.sh  runs, but doesn't listen on port 8080

T E S T S
-------------------------------------------------------
Running io.prometheus.jmx.TestJavaAgent
Tests run: 4, Failures: 0, Errors:

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
