### ISSUE TITLE
Failed to find Premain-Class manifest attribute jmx_prometheus_httpserver-0.13.1-SNAPSHOT-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by Kenzi007220** [prometheus/jmx_exporter#500]
Good day, I am trying to run the agent inside JBoss run,conf
`JAVA_OPTS="$JAVA_OPTS -javaagent:$JBOSS_HOME/jmx_prometheus_httpserver-0.13.1-SNAPSHOT-jar-with-dependencies.jar localhost:9595 $JBOSS_HOME/testhttp.yml"`

And testhttp.yml:
```
hostPort: localhost:5555
username: admin
password: admin
ssl: false
```
And having message in startup logs:
![image](https://user-images.githubusercontent.com/16799685/82431144-91c71b80-9a8e-11ea-8890-f4c6850919a3.png)
Start_error.log:
`Failed to find Premain-Class manifest attribute in /srv/backoffice/jboss/jmx_prometheus_httpserver-0.13.1-SNAPSHOT-jar-with-dependencies.jar`

Also the same situation with "jmx_prometheus_httpserver-0.13.0.jar" and "jmx_prometheus_httpserver-0.13.0-jar-with-dependencies.jar"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Kenzi007220** [comment]
Thanks

**Comment by MeirSolvo** [comment]
did you solve this?
