### ISSUE TITLE
JMX Exporter Operator + kubernetes + extra logging requested

### ISSUE THREAD

**Issue by v703612** [prometheus/jmx_exporter#506]
Dears,

We are trying to implement the JMX exporter operator through kubernetes yaml files, but we don't get it working. Is there any way we can achieve to have more logging, or do you see the issue already?

![image](https://user-images.githubusercontent.com/26733848/85256232-19c08c80-b464-11ea-9517-16f6cb409bde.png)

**Comment by brian-brazil** [comment]
This looks like a k8 question so it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
