### ISSUE TITLE
Can't find the config.yaml on run as javaagent

### ISSUE THREAD

**Issue by standup-jb** [prometheus/jmx_exporter#508]
In the readme.md 

`To run as a javaagent download the jar and run:
java -javaagent:./jmx_prometheus_javaagent-0.13.0.jar=8080:config.yaml -jar yourJar.jar
Metrics will now be accessible at http://localhost:8080/metrics`

But I can't find the file config.yaml , who can help me.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
