### ISSUE TITLE
JMX not captured continuously

### ISSUE THREAD

**Issue by ganeshs4** [prometheus/jmx_exporter#511]
The jmx metrics are not collected consistently. There are frequent gaps. The gaps were noticed for all Object Name/Mbeans.

For example (but it's for all JMX mbeans):
java_lang_Memory_HeapMemoryUsage_used
jvm_threads_current

I had enabled the logging. Anything specific to look for in the jmx_exporter logs? Any pointers

The logs are 212mb - https://drive.google.com/file/d/1UnQkWX4RIx5kJWR8GLbPes20CNRRMsqS/view?usp=sharing

**Comment by brian-brazil** [comment]
With a 10s scrape interval that's probably a timeout, so this sounds like a support question. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
