### ISSUE TITLE
Tomcat 9

### ISSUE THREAD

**Issue by Ayan189** [prometheus/jmx_exporter#514]
how to use jmx_exporter for Tomcat 9 and get metrics of tomcat on prometheus by using jmx_exporter.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
