### ISSUE TITLE
why ?  Data collection for Kafka Connect is incomplete

### ISSUE THREAD

**Issue by ccmanito** [prometheus/jmx_exporter#517]
why ?  Data collection for Kafka Connect is incomplete
MBean:  kafka.connect:type=connect-worker-metrics,connector="{connector}"

I would like to collect the data related to my Connector
I don't know why I need help，thank you

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
