### ISSUE TITLE
High CPU consumption

### ISSUE THREAD

**Issue by bshishir** [prometheus/jmx_exporter#519]
I am using JMX exporter for kafka related metrics. We are running it as javagent as shown below:-
export KAFKA_OPTS='-javaagent:/jmx/jmx_prometheus_javaagent-0.12.0.jar=7097:/kafka/kafka-jmx-metrics.yaml'

It shows high cpu usage(90%-100%) for a period of 20 minutes approx. once every day. Is it a known issue?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
