### ISSUE TITLE
What's the logic of checking if server is up

### ISSUE THREAD

**Issue by RoySunnySean007** [prometheus/jmx_exporter#521]
Dear JVM exporter experts,

I am using prometheus to collect JVM exporter metrics and visualize with Grafana. But there is no data in Grafana (and there is no data in prometheus as well). 
When there is no data, Grafana show the server is down. But I use prometheus to wget /metrics of that server successfully.
So I am a bit confused, what's the logic of checking if the server is up?
Really appreciate ur great help in advance!

![image](https://user-images.githubusercontent.com/32358517/91153362-b0bef480-e6f2-11ea-9176-b6fe5d63908d.png)

Thanks,
Roy

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
