### ISSUE TITLE
agent start error

### ISSUE THREAD

**Issue by ymydb** [prometheus/jmx_exporter#524]
../jdk/jdk1.8.0_241/bin/java -javaagent:/xmgl/jdk/jdk1.8.0_241/bin/jmx_prometheus_javaagent-0.3.1.jar=127.0.0.1:80:/xmgl/prometheus_agent_java/jmx_exporter.yml -jar /xmgl/rjb/yckp-0.0.1.jar 
Error opening zip file or JAR manifest missing : /xmgl/jdk/jdk1.8.0_241/bin/jmx_prometheus_javaagent-0.3.1.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
