### ISSUE TITLE
TabularData fields as labels

### ISSUE THREAD

**Issue by montrivo** [prometheus/jmx_exporter#530]
Hello,

I'm trying to export an MBean attribute that is a flat TabularData similar to this example:
```
| animal       | color        | metric       |
| horse        | blue         |            6 |
| frog         | blue         |            6 |
| cat          | blue         |            6 |
| cat          | red          |            6 |
```

I would like the exporter to print one metric per line in my table like this
```
animal_color_count{animal=horse, color=blue} 6
animal_color_count{animal=frog, color=blue} 4
animal_color_count{animal=cat, color=blue} 2
animal_color_count{animal=cat, color=red} 1
```

Is this possible? 
I don't understand well the part of the documentation describing composite and tabular data and I haven't found anything like this in the example files.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by montrivo** [comment]
As requested, I [asked] (https://groups.google.com/forum/m/#!searchin/prometheus-users/Tabular$20data/prometheus-users/koTrqZpmKhU) in the user group. There are no answers yet.
