### ISSUE TITLE
Setting Counter initial value to 0

### ISSUE THREAD

**Issue by in-park** [prometheus/jmx_exporter#532]
When using PromQL functions such as "increase", the initial value isn't considered during the calculation because the initial value isn't 0. It would be great if there could be a way to configure the initial value of the Counter through configuration.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
