### ISSUE TITLE
About some Hadoop metrics

### ISSUE THREAD

**Issue by angkorthomwdd** [prometheus/jmx_exporter#535]
Hi
      I have some questions about the Hadoop metrics.
      Why isn't there an metrics that tells me which one namenode is acticve or is standby of hadoop?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by angkorthomwdd** [comment]
OK,thanks
