### ISSUE TITLE
sonarqube 7.9 jmx scrape problem

### ISSUE THREAD

**Issue by frozzenn** [prometheus/jmx_exporter#538]
jmx_exporter does not collect some metrics from SonaQube ce component

`SonarQube_ComputeEngineDatabaseConnection*` metics are collected
`SonarQube_ComputeEngineTasks*` aren't

At the same time, the mbeans themselves are visible through the jconsole tool.

Looks like the problem appeared after upgrading sonarqube to version 7.9.

Output from jmx scraper
```
java -cp collector/target/collector-0.14.1-SNAPSHOT.jar -Djava.util.logging.config.file=log.prop io.prometheus.jmx.JmxScraper  service:jmx:rmi://127.0.0.1:4444/jndi/rmi://127.0.0.1:3333/jmxrmi

FINE: scrape: 'SonarQube:name=ComputeEngineTasks_[PendingCount, LongestTimePending, InProgressCount, ErrorCount, SuccessCount, ProcessingTime, WorkerMaxCount, WorkerCount, WorkerUuids, EnabledWorkerUuids]': Fail: java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
	java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: java.util.Optional
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
