### ISSUE TITLE
JMX exporter logging

### ISSUE THREAD

**Issue by Kenzi007220** [prometheus/jmx_exporter#552]
Good day, 
We are using Jboss6 and our application logs are located fe /var/log/boot.log file
after activating prometheus jmx exporter it is creating own new start.log and start_error.log in jboss home directory.

Do you know how to adjust the configuration to use application log path instead of own one?

**Comment by brian-brazil** [comment]
We use standard Java logging, so this is a question for your own existing log setup.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
