### ISSUE TITLE
exposing jdbc and jmx data

### ISSUE THREAD

**Issue by shayannyc25** [prometheus/jmx_exporter#558]
hi 
i need to expose jdbc and jms  jmx data  for my java programs. how can i configure  the yml config file for Prometheus jmx exporter to expose in its http service my jdbc and jms jmx data?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
