### ISSUE TITLE
JMX Exporters Metrics Issue

### ISSUE THREAD

**Issue by 02219290** [prometheus/jmx_exporter#566]
Team,

I have configured jmx exporter and Windows machine and the ports are opened, but still the metrics page is not opening with that port also not seeing the port is listening. Application is running fine on that server

Any suggestions to fix the same?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
