### ISSUE TITLE
CLOSE_WAIT

### ISSUE THREAD

**Issue by hr-ireh** [prometheus/jmx_exporter#567]
I have a lot of CLOSE_WAIT when using JavaAgent.
I am using JavaAgent on Tomcat.
I think the reason is this:
1. Data collection takes longer because my in-app processes are large on Tomcat.
2. The number of threads in simpleclient_httpserver is only 5.

Executors.newFixedThreadPool (5, HTTPServer.NamedDaemonThreadFactory.defaultThreadFactory (daemon))

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by yeyuguang1** [comment]
@hr-ireh Hi, brother, I have encountered the same problem. Have you solved it?
