### ISSUE TITLE
5 threads is bloke and close_wait connection

### ISSUE THREAD

**Issue by hr-ireh** [prometheus/jmx_exporter#568]
> 
> 
> > JMX exporter finishes collecting metrics, and attempts to write the output to the now-closed socket
> 
> That's not how TCP works, only one direction of the socket is closed. What exactly is netstat showing for these sockets? It also shouldn't be possible for there to be thousands of them, as there's only 5 worker threads.

All 5 thread are blocked but the connection is received because the thread is different from the connection.

![jmx_01](https://user-images.githubusercontent.com/20404639/103464606-55f57380-4d4a-11eb-9143-e43659010dd5.jpg)
![jmx_03](https://user-images.githubusercontent.com/20404639/103464643-a40a7700-4d4a-11eb-956f-92ed39f9eb22.jpg)

_Originally posted by @hr-ireh in https://github.com/prometheus/jmx_exporter/issues/327#issuecomment-753516675_

**Comment by brian-brazil** [comment]
This appears to be an issue with your application, not this exporter, as the trace is inside your application.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
