### ISSUE TITLE
snakeyaml vulnerability fix

### ISSUE THREAD

**Issue by 7vs** [prometheus/jmx_exporter#583]
A vulnerability scan of the prom/jmx-exporter image finds this.
CVE | SEVERITY | CVSS | PACKAGE | VERSION | STATUS | PUBLISHED | DISCOVERED | DESCRIPTION
-- | -- | -- | -- | -- | -- | -- | -- | --
CVE-2017-18640 | high | 7.50 | org.yaml_snakeyaml | 1.17 | fixed in 1.26 | > 10 months | < 1 hour | The Alias feature in SnakeYAML 1.18 allows entity expansion during a load operation, a related issue to CVE-2003-1564.
   @brian.brazil@robustperception.io

**Comment by fstab** [comment]
Thanks for reporting. I merged your PR for updating that dependency.

In case anyone reads this and is wondering how severe this is: I found a comment on [ubuntu.com/security/CVE-2017-18640](https://ubuntu.com/security/CVE-2017-18640) saying
> Upstream dispute this as a valid CVE - https://bitbucket.org/asomov/snakeyaml/issues/377/allow-configuration-for-preventing-billion#comment-55227358 - and they added a test-case for this type of attack of 2 years ago https://bitbucket.org/asomov/snakeyaml/commits/04378d05777d21d114a9cdc24976ad49c8919222 so this would appear to be a non-issue

Anyway, I didn't investigate further because 7vs already provided a PR with an updated for that dependency.
