### ISSUE TITLE
HTTP server listening in https 

### ISSUE THREAD

**Issue by pascalBrand** [prometheus/jmx_exporter#741]
Hi,

Is it planned to have a version with the HTTP server listening on https port ? 

Thanks,
Pascal

**Comment by dhoard** [comment]
See https://github.com/prometheus/jmx_exporter/issues/688

**Comment by dhoard** [comment]
@pascalBrand I have been working on the initial code to support HTTPS.

 A **potential** pre-release version of code can be found at...

https://github.com/dhoard/jmx_exporter/releases/tag/jmx_exporter_enhanced-snapshot.

Due to the vast number of changes, it will take time to be merged and released.

**Comment by dhoard** [comment]
@pascalBrand I have been working on the initial code to support HTTPS.

 A **potential** pre-release version of code can be found at...

https://github.com/dhoard/jmx_exporter/releases/tag/jmx_exporter_enhanced-snapshot.

Due to the vast number of changes, it will take time to be merged and released.

**Comment by dhoard** [comment]
Resolved in release 0.19.0.
