### ISSUE TITLE
Is there a metric like jmx_up something similar to other standard exporters like mysql_up, mongodb_up or pg_up

### ISSUE THREAD

**Issue by acharbha** [prometheus/jmx_exporter#887]
Is there a metric like jmx_up something similar to other standard exporters like mysql_up, mongodb_up or pg_up
I couldn't find it. 
What Prometheus expression can indentify where ActiveMQ instance is down ?

**Comment by dhoard** [comment]
There is not.

When running as a Java agent (recommended), if the application is down, then the Prometheus scrape to the exporter will fail (no response) since it runs as part of the Java application.

When running as a standalone exporter (not recommended), if the application is down, the exporter will increase the `jmx_scrape_error` metric and return minimal metrics.
